services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: superdupersecretpoyowebdatabasetestpasswordthatwewillabsolutelyhidefromothers(this isnt a true production password dw)
      POSTGRES_DB: local
